#-------------------------------
# General Site Settings
title: Celebrant Media
#logo: celebrant.png # You can add own logo.
description: Digital media for real brands.


#-------------------------------
# Author Settings
author:
  name: Parav K Singla
  image: home.jpg
  say-hello: Hello, We're <strong>Celebrant</strong>
  bio: We create video and images for personal brands and small businesses.


#-------------------------------
# Contact links
twitter: https://twitter.com/ # Add your Twitter handle
facebook: https://facebook.com/ # Add your Facebook handle
dribbble: https://dribbble.com/ # Add your Dribbble handle
instagram: https://instagram.com/ # Add your Instagram handle
pinterest: https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: https-celebrantmedia-com # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: UA-157021582-4 # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: celebrantmedia.us19.list-manage.com/subscribe/post?u=daeacd7c97db4f33775d58f64&amp;id=5abd68fcf2 # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
